config/routes.rb
Abstractify::Application.routes.draw do

  resources :conferences do
    get :download_pdfs, :on => :member
  end
  
  resources :submissions do
    get :download_pdf, :on => :member
  end

  devise_for :users
  
  resources :faqs
  
  root :to => "conferences#index"

end

app/models/conference.rb
class Conference < ActiveRecord::Base
  has_many :submissions
  
  default_scope order('submission_deadline DESC')
  
  scope :accepting_submissions, where("conferences.submission_deadline >= ?", Time.now)
  
  validates :name, :start_date, :end_date, :submission_deadline, :presence => true
  
  def accepting_submissions?
    return true if submission_deadline >= Time.now
    false
  end
  
  def pdf_filename
    self.name.gsub(/[^0-9A-Za-z]/, '_') + "_" + Time.now.to_i.to_s
  end
end


# == Schema Info
#
# Table name: conferences
#
#  id                  :integer         not null, primary key
#  end_date            :date
#  name                :string(255)
#  start_date          :date
#  submission_deadline :datetime
#  created_at          :datetime
#  updated_at          :datetime

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :conference
  belongs_to :user
  
  has_attached_file :image, :styles => { :pdf => "380x380>" }
  
  process_in_background :image
  
  validates_attachment_content_type :image, 
                                    :content_type => ['image/jpeg', 'image/png', 'image/gif']
                                    
  validates :image_file_name, :format => { 
                                          :with => /^[a-zA-Z-0-9]\S*$/, 
                                          :message => "cannot contain spaces or special characters." 
                                         }, :if => :has_image?
                              
  validates :title, :authors, :institutions, :body, :user_id, :conference_id, :presence => true
  validates :title, :authors, :institutions, :length => { :maximum => 255 }
  validates :body, :length => { :maximum => 1650 }
  validates :title, :uniqueness => true
  
  before_save :validates_conference_is_accepting_submissions
  
  attr_protected :user_id
  
  def pdf_filename
    self.title.gsub(/[^0-9A-Za-z]/, '_') + "_" + Time.now.to_i.to_s
  end
  
  def has_image?
    !image_file_name.nil?
  end
  
  private
  
  def validates_conference_is_accepting_submissions
    errors.add(:conference_id, "is not accepting submissions.") unless
      Conference.find(conference_id).accepting_submissions?
  end
end


# == Schema Info
#
# Table name: submissions
#
#  id                 :integer         not null, primary key
#  conference_id      :integer
#  user_id            :integer
#  authors            :string(255)
#  body               :text
#  image_content_type :string(255)
#  image_file_name    :string(255)
#  image_file_size    :integer
#  institutions       :string(255)
#  title              :string(255)
#  created_at         :datetime
#  image_updated_at   :datetime
#  updated_at         :datetime

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :submissions
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  def role_symbols  
    return [:admin] if admin?
    [:user]
  end
end


# == Schema Info
#
# Table name: users
#
#  id                   :integer         not null, primary key
#  admin                :boolean
#  current_sign_in_ip   :string(255)
#  email                :string(255)     not null, default("")
#  encrypted_password   :string(128)     not null, default("")
#  last_sign_in_ip      :string(255)
#  password_salt        :string(255)     not null, default("")
#  remember_token       :string(255)
#  reset_password_token :string(255)
#  sign_in_count        :integer         default(0)
#  created_at           :datetime
#  current_sign_in_at   :datetime
#  last_sign_in_at      :datetime
#  remember_created_at  :datetime
#  updated_at           :datetime

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  

end

app/controllers/conferences_controller.rb
class ConferencesController < InheritedResources::Base
  actions :index, :download_pdfs
  
  def download_pdfs
    @conference = Conference.find(params[:id])
    pdf = render_to_string(:action => 'all_submissions', :layout => false)
    pdf = PDFKit.new(pdf)
    send_data(pdf.to_pdf, :filename => @conference.pdf_filename)
  end
end

app/controllers/faqs_controller.rb
class FaqsController < InheritedResources::Base
  actions :only => :index
end

app/controllers/submissions_controller.rb
class SubmissionsController < InheritedResources::Base
  before_filter :authenticate_user!
  respond_to :js, :only => :show
      
  def index
    if current_user.admin?
      @submissions = Submission.all
    else
      @submissions = current_user.submissions
    end
    
    @grouped_submissions = @submissions.group_by { |t| t.conference }
  end
  
  def download_pdf
    @submission = Submission.find(params[:id])
    pdf = render_to_string(:action => 'download_pdf', :layout => false)
    pdf = PDFKit.new(pdf)
    send_data(pdf.to_pdf, :filename => @submission.pdf_filename)
  end

  protected

  def begin_of_association_chain 
    request.get? ? super : current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def current_user_is_admin?
    return User.find(current_user).admin? if user_signed_in?
    false
  end
end

app/helpers/conferences_helper.rb
module ConferencesHelper
  
  def render_conference(conference)
    return render :partial => 'conference', :locals => { :conference => conference } if conference.accepting_submissions?
    content_tag :li, conference.name
  end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/conferences/_conference.html.erb
<li class="accepting_submissions">
  <section>
    <header>
      <h1>
        <%= conference.name %>
      </h1>
      <% if current_user_is_admin?  %>
        <%= link_to "Download all PDFs for conference.", download_pdfs_conference_path(conference)%>
      <% end %>
    </header>
    <p>
      <%= conference.start_date.strftime("%b %d") %> &mdash; <%= conference.end_date.strftime("%b %d") %>
    </p>
    <p class="year"><%= conference.start_date.strftime("%Y") %></p>
    <p class="submission_deadline">
      Submission Deadline: <%= conference.submission_deadline.to_s(:submission_deadline) %>
    </p>
    <%= link_to "Submit an abstract", new_submission_path(:conference => conference.id), :class => :abstract_link %>
  </section>
</li>

app/views/conferences/all_submissions.html.erb
<div>
    <h1>
      <%= @conference.name %>
    </h1>
  <p>
    <%= @conference.start_date.strftime("%b %d") %> &mdash; <%= @conference.end_date.strftime("%b %d") %>
  </p>
  <p class="year"><%= @conference.start_date.strftime("%Y") %></p>
  <p class="submission_deadline">
    Submission Deadline: <%= @conference.submission_deadline.to_s(:submission_deadline) %>
  </p>
</div>

<div>
  <h1>Submissions</h1>
  <p><%= pluralize(@conference.submissions.count, "submission") %></p>
  <hr />
  
  <% @conference.submissions.each do |submission| %>
    <div style="page-break-after: always;">
      <h1><%= submission.title %></h1>

      <p><%= submission.authors %></p>
      <p><%= submission.institutions %></p>
      <div id="body">
        <%= raw RedCloth.new(submission.body, [:filter_html]).to_html %>
      </div>
      <%= image_tag submission.image.path(:pdf) if submission.has_image? %>
    </div>
  <% end %>
</div>

app/views/conferences/index.html.erb
<% content_for :header do %>
  <h1>Conferences</h1>
<% end %>

<ol id="conferences">
  <% @conferences.each do |conference| %>
    <%= render_conference(conference) %>
  <% end %>
</ol>

app/views/conferences/show.html.erb
<% content_for :header do %>
  <hgroup>
    <h1><%= @conference.name %></h1>
    <h2>      
      <%= @conference.start_date.strftime("%b %d, %Y") %> &mdash; <%= @conference.end_date.strftime("%b %d, %Y") %>
    </h2>
  </hgroup>
<% end %>

<section id="submissions">
  <header>
    <h1>Abstracts</h1>
  </header>
  <ul>
    <% @conference.submissions.each do |submission| %>
      <li><%= link_to submission.title, submission %></li>
    <% end %>
  </ul>
</section>

<% content_for :sidebar do %>
  <aside>
    <% if @conference.accepting_submissions? %>
      <%= link_to "Submit an abstract", new_submission_path(:conference => @conference.id), :class => :submit_abstract_link %>
    <% end %>
  </aside>
<% end %>

app/views/faqs/index.html.erb
<h1>Frequently Asked Questions</h1>
<br/>
<h2>How many characters to an abstract?</h2>
<p>1650, including white space.</p>
<br/>
<h2>Does the character limit include white space?</h2>
<p>Yes</p>
<br/>
<h2>How do I insert special characters?</h2>
<p>Just type the code for the character.  The code counts against your character count too.  We increased the character limit from 1600 to 1650 to compensate for the white space and special characters.</p>
<h3>An example for inserting a special character.</h3>
<p>This is the code for &#916;&ndash;&amp;#916;.  Codes always start with &amp;# and end with a semicolon.  The three digits in the middle dictate the special character.  You may find more codes <a href="http://htmlhelp.com/reference/html40/entities/symbols.html">here</a>.
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abstractify</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
    <div id="user_block">
      <div>
        <nav>
          <%= link_to "Conferences", conferences_path %>
 
          <%  unless Conference.accepting_submissions.blank? %>
            |
            <%= link_to "New Submission", new_submission_path %>
          <% end %>
          
          <% if user_signed_in? %>
            | 
            <%= link_to "My Submissions", submissions_path unless current_user.admin? %>
            <%= link_to "All Submissions", submissions_path if current_user.admin? %>
          <% end %>
          | <%= link_to "FAQ", faqs_path %>
        </nav>
        
        <% if user_signed_in? %>
          <p>
            logged in as <%= current_user.email %> |
            <%= link_to 'logout', destroy_user_session_path %>
          </p>
        <% end %>
      </div>
    </div>

  <article id="page">
    <header id="main_header">
      <%= yield(:header) %>
    </header>
    <p id="notice"><%= notice %></p>
    
    <section id="main_content">
      <%= yield %>
    </section>

    <%= yield(:sidebar) %>
  </article>
  

  <footer>
    <p>
    &copy; 2011, <a href="http://physiology.umc.edu">University of Mississippi Medical Center Department of Physiology and Biophysics</a>
    </p>
  </footer>
</body>
</html>

app/views/layouts/maintenance.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Abstractify | Down for <%= reason ? reason : "maintenance" %>.</title>
  <style type="text/css">
    /* ================ */
    /* = The 1Kb Grid = */
    /* 12 columns, 60 pixels each, with 20 pixel gutter */
    /* ================ */
    .grid_1 {
      width: 60px; }

    .grid_2 {
      width: 140px; }

    .grid_3 {
      width: 220px; }

    .grid_4 {
      width: 300px; }

    .grid_5 {
      width: 380px; }

    .grid_6, body div {
      width: 460px; }

    .grid_7 {
      width: 540px; }

    .grid_8 {
      width: 620px; }

    .grid_9 {
      width: 700px; }

    .grid_10 {
      width: 780px; }

    .grid_11 {
      width: 860px; }

    .grid_12 {
      width: 940px; }

    .column {
      margin: 0 10px;
      overflow: hidden;
      float: left;
      display: inline; }

    .row {
      width: 960px;
      margin: 0 auto;
      overflow: hidden; }
      .row .row {
        margin: 0 -10px;
        width: auto;
        display: inline-block; }

    body {
      color: #242833;
      font-family: Helvetica, arial, sans-serif;
      line-height: 24px; }
      body div {
        margin: 0 auto; }
        body div h1 {
          margin-top: 100px;
          font-size: 48px; }
      body div#message {
        padding: 2em;
        border: 14px solid #d7ecf4;
        background-color: #f2efbd;
        text-align: center; }
    
  </style>
</head>
<body>
  <div>
    <h1>Abstractify</h1>
    
    <div id="message">
      <h2>down for maintenance.</h2>
      <p>
        We're sorry for the inconvenience.
        We'll be back <%= deadline ? "by #{deadline}" : "shortly" %>.
      </p>
    </div>

  </div>
</body>
</html>

app/views/submissions/_form.html.erb
<%= form_for(@submission, :html => { :multipart => true }) do |f| %>
  <% if @submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% @submission.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <fieldset id="author_info">
    <legend>Author Information</legend>
    
    <dl>
      <dt><%= f.label :names %></dt>
      <dd><%= f.text_field :authors, :required => true, :placeholder => "Limit is 255 characters" %></dd>


      <dt><%= f.label :institutions %></dt>
      <dd><%= f.text_field :institutions, :required => true, :placeholder => "Limit is 255 characters" %></dd>
    <dl>
  </fieldset>
  
  <% if params[:conference].blank? %>
    <fieldset>
      <legend>Conference</legend>
      
      <%= f.collection_select :conference_id, Conference.accepting_submissions, :id, :name, :prompt => "Select one" %>
    </fieldset>
  <% end %>
  
  <fieldset id="abstract_info">
    <legend>Abstract</legend>
    
    <dl>
      <dt><%= f.label :title %></dt>
      <dd><%= f.text_field :title, :required => true, :placeholder => "Limit is 255 characters" %></dd>

      <dt><%= f.label :body %></dt>
      <dd><%= f.text_area :body, :required => true, :placeholder => "Limit is 1600 characters" %><dd>
    </dl>
  </fieldset>
  
  <fieldset>
    <legend>Image</legend>
    <%= f.file_field :image, :class => :image %>
  </fieldset>


  <%= f.hidden_field :conference_id, :value => params[:conference] unless params[:conference].blank? %>

    <%= f.submit "Submit Abstract" %> or <%= link_to 'Cancel', submissions_path %>
<% end %>

app/views/submissions/_image.html.erb
<span id="<%= @submission.image_processing ? 'missing_image' : 'image' %>" data-id="<%= @submission.id %>">
  <%= image_tag @submission.image.url(:pdf) %>
</span>

app/views/submissions/_redcloth_help.html.erb
<section>
  <header>
    <h1>Form Constraints</h1>
  </header>
  <ul>
    <li>Author names, institutions, and Abstract title cannot exceed 255 characters.</li>
    <li>Abstract body cannot exceed 1650 characters.</li>
    <li>Image filenames cannot contain spaces or special characters.</li>
  </ul>
</section>

<section>
  <header>
    <h1>Special Characters</h1>
  </header>
  <p>The form uses <a href="http://redcloth.org" class="standard">Redcloth</a> to allow html formatting inside your submission.  As a result, you may use HTML codes for inputing symbols.  A list of html codes for symbols and Greek letters may be found <a href="http://htmlhelp.com/reference/html40/entities/symbols.html" class="standard"> here</a>.  The html code for &#177; is &amp;#177.</p>

</section>

app/views/submissions/_submission.html.erb
<div id="pdf_wrapper">
  <h1><%= @submission.title %></h1>
  
  <p><%= @submission.authors %></p>
  <p><%= @submission.institutions %></p>
  <div id="body">
    <%= raw RedCloth.new(@submission.body, [:filter_html]).to_html %>
  </div>
  <%= image_tag @submission.image.path if @submission.has_image? %>
</div>

app/views/submissions/download_pdf.html.erb
<div id="pdf_wrapper">
  <h1><%= @submission.title %></h1>
  
  <p><%= @submission.authors %></p>
  <p><%= @submission.institutions %></p>
  <div id="body">
    <%= raw RedCloth.new(@submission.body, [:filter_html]).to_html %>
  </div>
  <%= image_tag @submission.image.path(:pdf) if @submission.has_image? %>
</div>

app/views/submissions/edit.html.erb
<h1>Editing submission</h1>

<%= render 'form' %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<% content_for :header do %>
  <h1>All Submissions</h1>
<% end %>

<ul id="grouped_submissions">
  <% @grouped_submissions.each do |conference, submissions| %>
    <li class="conference">
      <hgroup>
        <h1><%= conference.name %></h1>
        <h2>
          <%= conference.start_date.strftime("%b %d, %Y") %> &mdash; <%= conference.end_date.strftime("%b %d, %Y") %>
        </h2>
      </hgroup>
      <ul>
        <% for submission in submissions %>
          <li><%= link_to submission.title, submission %> | <%= link_to 'Download PDF', download_pdf_submission_path(submission) %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/submissions/new.html.erb
<% content_for :header do %>
  <h1>
    New Submission
    
    <% unless params[:conference].blank? %>
      for <%= Conference.find(params[:conference]).name %>
    <% end %>
  </h1>
<% end %>

<%= render 'form' %>

<% content_for :sidebar do %>
  <aside>
    <%= render 'redcloth_help' %>
  </aside>
<% end %>

app/views/submissions/pdf.html.erb
<%= render 'submission' %>

app/views/submissions/show.html.erb
<% content_for :header do %>
  <hgroup>
    <h1><%= @submission.title %></h1>
    <h2>Conference: <%= @submission.conference.name %></h2>
  </hgroup>
<% end %>

<div id="abstract_body">
  <p id="authors"><%= @submission.authors%></p>
  <p id="institutions"><%= @submission.institutions %></p>

  <%= raw RedCloth.new(@submission.body, [:filter_html]).to_html %>
  
  <%= render 'image' if @submission.has_image? %>
</div>


<% content_for :sidebar do %>
  <aside>

  <% if user_signed_in? %>
    <% if @submission.user_id == current_user.id %>
      <nav>
        <ul>
          <li>
            <%= link_to 'Edit', edit_submission_path(@submission) %> 
          </li>
          <li>
          <%= link_to 'Destroy', @submission, :confirm => 'Are you sure?', :method => :delete %>
          </li>
        </ul>
      </nav>

    <% end %>
  <% end %>

  <%= link_to 'Download PDF', download_pdf_submission_path(@submission), :class => :pdf_link %>
  </aside>
<% end %>

app/views/submissions/show.js.erb
$("#missing_image").replaceWith("<%= escape_javascript(raw render('image')) %>");